[build]
  command = "npm run build"
  functions = ".next/serverless"  # Auto-généré par Next.js
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true